# Generated by Django 3.2.4 on 2021-07-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210707_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, default='uploads/cover_pictures/default_cover.png', upload_to='uploads/cover_pictures'),
        ),
    ]
