# Generated by Django 3.2.4 on 2021-07-23 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userNotifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
